# This is a basic workflow to help you get started with Actions

name: delete deployment on PR Merged

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
        - develop
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    if: github.event.pull_request.merged == true
    steps:
    - name: HTTP Request Action
      # You may pin to the exact commit or the version.
      # uses: fjogeleit/http-request-action@0929a0c636cc8dc6ba7715f5b3d90b0655ded3d7
      env:
       PR_NUMBER: ${{ github.event.number }}
       BUDDY_TOKEN: ${{ secrets.BUDDY_TOKEN }}
      run: |
        curl --location --request POST "https://app.buddy.works/knawat/mpadmin/pipelines/pipeline/320876/trigger-webhook?token=$BUDDY_TOKEN" --header 'Content-Type: application/x-www-form-urlencoded'  --data-urlencode "myenv=$PR_NUMBER"
